# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_d91fc7db6cc1b6edb2d59b8f9987005de892090c
# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,controllers,helpers,middlewares,models,routes,config
sonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info
sonar.exclusions=**/*.test.js,tests/**
